#!/usr/bin/python3

#################################
#  Buffer Overflow Template     #
#  Created by John Lavery       #
#  Year of 2019                 #
#  Written in Python 3.8        #
#################################

import requests
import os
import time

fn = input("File name?: ")

os.system('clear')
with open(fn) as f:
  urls = f.read().splitlines()

for url in urls:
  r = requests.get(url,verify=False)
  print ("\n" + url+": "+r.headers['server'])
  print (r.elapsed.total_seconds())
