############################################################################################################
#  Vyos Router Factory Reset Playbook                                                                      #
#  Created by John Lavery                                                                                  #
#  Year of 2023                                                                                            #
#  Ansible Playbook                                                                                        #
#  Description:                                                                                            #
#  A playbook that can be used to backup the current config into a backup_configs directory, remove the    #
#  current config and reboot.                                                                              #
#                                                                                                          #
# WARNING: Make sure you have kvm console access to the router after this playbook is ran or you will have #
# issues with trying to setup a new config.                                                                #
############################################################################################################



# Perform backup, copy, and reboot tasks playbook

- name: Perform backup, copy, and reboot tasks
  hosts: all
  become: yes  # Run tasks with elevated privileges using sudo

  tasks:
    # Task to create a backup directory
    - name: Create backups directory
      shell: mkdir -p /config/backup_configs

    # Task to copy config.boot to backups directory and remove the original
    - name: Copy config.boot to backups directory and remove the original
      shell: 
        cmd: |
          cp /config/config.boot /config/backup_configs 
          rm /config/config.boot 
      when: inventory_hostname == '192.168.203.190'  # Only execute on specific host

    # Task to reboot vyos (uses sudo)
    - name: Reboot vyos
      become: yes 
      reboot:



# inventory file to make this work:
#
# [all]
#192.168.203.190 ansible_user=vyos ansible_password=vyos
